---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-concept-taxonomy
    sas.com/admin: namespace
  name: sas-concept-taxonomy
spec:
  routes:
  - conditions:
    - prefix: /conceptTaxonomy
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /conceptTaxonomy/
    services:
    - name: sas-concept-taxonomy
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /conceptTaxonomy/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-concept-taxonomy
      port: 80
    timeoutPolicy:
      response: 300s

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-concepts
    sas.com/admin: namespace
  name: sas-concepts
spec:
  routes:
  - conditions:
    - prefix: /concepts
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /concepts/
    services:
    - name: sas-concepts
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /concepts/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-concepts
      port: 80
    timeoutPolicy:
      response: 300s

