apiVersion: orchestration.sas.com/v2beta4
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-rabbitmq-server
    sas.com/component-version: 3.1009001.4-20221216.1671199842998
  creationTimestamp: null
  name: deploy-pre-rabbitmq
spec:
  args:
  - name: namespace
  - name: timeout
  steps:
  - args:
    - deploy-pre-rabbitmq-execute
    - --namespace
    - $namespace
    - --timeout
    - $timeout
    cmd: run
    when: |-
      (eq
        "true"
        (.Annotation "sas.com/sas-rabbitmq-server-update" (.ClusterResource ((((((.NewClusterResourcesIterationSpec).WithNamespace $namespace).WithGroup "").WithVersion "v1").WithResource "configmap").WithName "sas-deploy-lifecycle-operation-variables")))
      )
