apiVersion: orchestration.sas.com/v2beta5
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-rabbitmq-server
    sas.com/component-version: 3.1009001.4-20221216.1671199842998
  creationTimestamp: null
  name: deploy-assess-rabbitmq-execute
spec:
  args:
  - name: namespace
  steps:
  - args:
    - annotate
    - --namespace
    - $namespace
    - configmap
    - sas-deploy-lifecycle-operation-variables
    - sas.com/sas-rabbitmq-server-update=true
    cmd: kubectl
