apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-orchestration
    sas.com/component-version: 1.86.3-20221216.1671216783534
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/assess: "true"
  name: kubernetes-kubectl-server-version-alignment-check
spec:
  steps:
  - args:
    - kubectl and server version combination exceed the supported skew window
    cmd: fail
    when: (not (.KubernetesClientServerVersionsAreValid))
