apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-k8s-common
    sas.com/component-version: 2.60.2-20221212.1670880199432
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/start-all-execute-phase-0: "true"
  name: start-all-execute-postgres
spec:
  args:
  - name: namespace
  steps:
  - args:
    - patch
    - --namespace
    - $namespace
    - postgresclusters.postgres-operator.crunchydata.com
    - $resource.Name
    - --type
    - json
    - --patch
    - '(print "[{\"op\":\"replace\", \"path\": \"/spec/shutdown\", \"value\":" (.LastAppliedConfigurationValue $resource "{.spec.shutdown}" "false") "}]" )'
    cmd: kubectl
    when: (.ClusterDefinitions (((.NewClusterDefinitionsIterationSpec).WithGroup "postgres-operator.crunchydata.com").WithResource "postgresclusters"))
    withClusterResources:
      group: postgres-operator.crunchydata.com
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: postgresclusters
      version: v1beta1
