
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-49af660b4f8b8de5
patch: |-
  - op: add
    path: /spec/selector/matchExpressions
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d5d0f6d7bddd30c4
patch: |-
  - op: add
    path: /spec/template/spec/initContainers
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-ee82af2b1a7f2149
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7419409af5665779
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-76e5356d103d6765
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-27c887c866de7d5b
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/livenessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-6dd48b769d5bbe0a
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/readinessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-eb05da3570c585ff
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/startupProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-403e87b8c268d93e
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-a681c41be6b629d6
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/supplementalGroups
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-51c742a79ef4f105
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/sysctls
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-2251785ee7aeff63
patch: |-
  - op: add
    path: /spec/template/spec/imagePullSecrets
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-4e0e06693d3e1416
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-364028d27cae7947
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-e9bcfdb539620424
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/1/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-8004699265cd686e
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d298ce2991fd696a
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/namespaces
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-8f796c433b930e1c
patch: |-
  - op: add
    path: /spec/template/spec/hostAliases
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-323bb62e2a6ea43e
patch: |-
  - op: add
    path: /spec/template/spec/readinessGates
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-documents
  version: v1
