apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-archive-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ STORAGE-CAPACITY }} # Change this to desired capacity.
  storageClassName: {{ STORAGE-CLASS }} # Change this the desired storage class.