---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-sentiment-execution-provider
    sas.com/admin: namespace
  name: sas-sentiment-execution-provider
spec:
  routes:
  - conditions:
    - prefix: /sentimentExecutionProvider
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /sentimentExecutionProvider/
    services:
    - name: sas-sentiment-execution-provider
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /sentimentExecutionProvider/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-sentiment-execution-provider
      port: 80
    timeoutPolicy:
      response: 300s

