commonLabels:
  app.kubernetes.io/name: pgo
  app.kubernetes.io/version: 5.2.1

bases:
- ../crd
- ../rbac/namespace
- ../manager

patchesJson6902:
- target: { group: apps, version: v1, kind: Deployment, name: pgo }
  path: selectors.yaml
- target: { group: apps, version: v1, kind: Deployment, name: pgo-upgrade }
  path: selectors.yaml

patchesStrategicMerge:
- manager-target.yaml
- manager-target-upgrade.yaml