apiVersion: builtin
kind: PatchTransformer
metadata:
  name: crunchy-upgrade-platform-postgres-transformer
patch: |-
  - op: add
    path: /spec/dataSource
    value:
      volumes:
        pgDataVolume:
          pvcName: sas-crunchy-data-postgres
          directory: "sas-crunchy-data-postgres"
        pgBackRestVolume:
          pvcName: sas-crunchy-data-postgres-pgbr-repo
          directory: "sas-crunchy-data-postgres-backrest-shared-repo"
target:
  group: postgres-operator.crunchydata.com
  kind: PostgresCluster
  name: sas-crunchy-platform-postgres
  version: v1beta1