---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo-upgrade
  labels:
    postgres-operator.crunchydata.com/control-plane: postgres-operator-upgrade
    sas.com/zero-scale-phase: "1"
  annotations: {}
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/control-plane: postgres-operator-upgrade
  template:
    metadata:
      labels:
        postgres-operator.crunchydata.com/control-plane: postgres-operator-upgrade
      annotations:
        sas.com/certificate-file-format: pem
    spec:
      imagePullSecrets: []
      initContainers: []
      volumes: []
      containers:
      - name: operator
        image: sas-crunchy5-postgres-operator-upgrade
        env:
        - name: PGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: [ALL] }
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: postgres-operator-upgrade
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
          - weight: 50
            preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless